before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

merge_request_verify:
  image: node:12-alpine
  stage: dependencies
  script:
    - npm install
  only:
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules  
    
deploy_staging:
  type: deploy
  environment:
    name: staging
    url: http://dev.profakounda.com/
  script:
    - ssh ubuntu@51.83.68.188 "cd /var/www/profakounda-front-dev &&sudo git checkout . &&sudo git pull origin develop &&sudo rm package-lock.json &&sudo npm install &&sudo ng build --configuration=dev && exit"
  only:
    - develop

deploy_prod:
  type: deploy
  environment:
    name: production
    url: http://profakounda.com/
  script:
    - ssh ubuntu@51.83.68.188 "cd /var/www/prof-akounda-front &&sudo git pull origin master &&sudo rm package-lock.json &&sudo npm install &&sudo ng build --configuration=production && exit"
  only:
    - master
